packages:
  - apps/*
  - packages/*

catalog:
  '@convex-dev/better-auth': ^0.10.9
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@types/react': 19.2.2
  '@types/react-dom': 19.2.2
  better-auth: 1.4.9
  convex: ^1.31.2
  dotenv: ^17.2.3
  next: 16.0.0
  react: 19.2.0
  react-dom: 19.2.0
  tsdown: ^0.15.5
  zod: 4.1.12

onlyBuiltDependencies:
  - esbuild
  - sharp
