packages:
  - apps/*
  - packages/*

catalog:
  '@convex-dev/better-auth': ^0.10.9
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.5.0
  '@types/node': 25.0.5
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  better-auth: ^1.4.10
  convex: ^1.31.3
  dotenv: ^17.2.3
  next: 16.1.1
  react: 19.2.3
  react-dom: 19.2.3
  tsdown: ^0.15.5
  typescript: 5.9.3
  zod: ^4.3.5

onlyBuiltDependencies:
  - esbuild
  - sharp
